//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checks
    {
        public int Id { get; set; }
        public Nullable<int> RecordId { get; set; }
        public Nullable<decimal> GuestBill { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public Nullable<decimal> BonusesReceived { get; set; }
    
        public virtual PaymentMethods PaymentMethods { get; set; }
        public virtual Records Records { get; set; }
    }
}
